config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('fitness.urls')),
    path('', include('user.urls'))
    # path('admin/', admin.site.urls)
]

fitness/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path('', views.index, name=""),                     # 메인
    path('withfit/', views.index, name="index"),        # 메인
    path('get_rank/', views.get_rank),                  # 메인-랭킹json

    path('select/', views.select, name='select'),       # 운동, 인원 수 선택
    path('player/', views.player, name='player'),       # Ajax
    
    path('play/', views.play, name='play'),             # 플레이
    path('result/', views.result, name='result'),       # 결과화면
    path('get_result/', views.get_result)               # 결과화면-랭킹json
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout')
]

fitness/models.py
from django.db import models

class Fitness(models.Model):
  fitness_index = models.BigAutoField(primary_key=True)
  fitness_name = models.CharField(max_length=100)
  guide = models.TextField(default="")
  video = models.CharField(max_length=1000, null=True)

  class Meta:
    managed = True
    db_table = 'fitness'


class Monster(models.Model):
  monster_index = models.BigAutoField(primary_key=True)
  monster_name = models.CharField(max_length=100)
  monster_health = models.IntegerField()
  # monster_filename = models.CharField(max_length=300)

  class Meta:
    managed = True
    db_table = 'monster'


class Item(models.Model):
  item_index = models.BigAutoField(primary_key=True)
  item_name = models.CharField(max_length=100)
  item_filename = models.CharField(max_length=1000)

  class Meta:
    managed = True
    db_table = 'item'

fitness/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponseRedirect, JsonResponse

from django.db.models.expressions import Window
from django.db.models.functions import RowNumber
from django.db.models import F
from django.core import serializers

from user.models import User
from rank.models import Rank
from fitness.models import Fitness

import json

def index(request):
  return render(request, 'index.html')

def get_rank(request):
  num = 4
  rank = Rank.objects.order_by('-rank_score')[:num]

  rank_data = serializers.serialize('json', rank, fields={'rank_user_name', 'rank_score', 'rank_fitness_name', 'option'})
  rank_data = json.loads(rank_data)
  rank_data = [{**item['fields'], **{'pk': item['pk']}} for item in rank_data]
  context = {
    'num': num,
    'rank_data': rank_data
  }

  return JsonResponse(context)


def select(request):
  return render(request, 'fitness/select.html')


def player(request):
  return render(request, 'fitness/player.html')


def play(request):
  if request.method == 'POST':
    # 선택된 운동
    exercise_name = request.POST.get('exercise')

    # 선택된 인원수
    player = request.POST.get('selected_p')

    fitness = Fitness.objects.get(fitness_name = exercise_name)
    fitness_index = fitness.fitness_index

    context = {
      'exercise_name': exercise_name,
      'player': player,
      'fitness_index': fitness_index
    }
    
    if player == '1':
      return render(request, 'fitness/play.html', context)
    elif player == '2':
      return render(request, 'fitness/play2p.html', context)

  else:
    return HttpResponseRedirect('fitness:index')


def play2p(request):
  if request.method == 'POST':
    # 선택된 운동
    exercise_name = request.POST.get('exercise')
    

def result(request):
  if request.method == 'POST':
    score = request.POST.get('score')
    option = request.POST.get('option')
    fitness_name = request.POST.get('fitness_name')
    user_name = request.POST.get('user_name')
    fitness_index = int(request.POST.get('fitness_index'))
    user_index = int(request.POST.get('user_index'))
    stage = request.POST.get('stage')

    message = ''

    try:
      rank = Rank.objects.get(user_index=user_index, fitness_index=fitness_index)
      if score > rank.rank_score:
        rank.rank_score = score
        rank.save()
        message = '기록 갱신!!'
      else:
        message = '기록 갱신 실패'
    except Exception as e:
      rank = Rank(rank_score=score,
            option=option,
            rank_fitness_name=fitness_name,
            rank_user_name=user_name,
            fitness_index=Fitness.objects.get(fitness_index=fitness_index),
            user_index=User.objects.get(user_index=user_index),
            stage=stage
        )
      rank.save()

    context = {
      'user_index': user_index,
      'message': message
    }

    return render(request, 'fitness/result.html', context)
    
  return HttpResponseRedirect('fitness:index')

def get_result(request):
  # result_rank = Rank.objects.annotate(
  #   row_number=Window(
  #     expression=RowNumber(),
  #     partition_by=[F('rank_index')],
  #     order_by=F('rank_score').desc()
  #   )).order_by('row_number', 'rank_score')

  result_rank = Rank.objects.order_by('-rank_score')
  
  result_data = serializers.serialize('json', result_rank, fields={'rank_user_name', 'rank_score', 'rank_fitness_name', 'stage', 'option'})
  result_data = json.loads(result_data)
  result_data = [{**item['fields'], **{'pk': item['pk']}} for item in result_data]

  context = {
    'result_data': result_data
  }

  return JsonResponse(context)

templates/fitness/play.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_SD.css' %}"/>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript" src="{% static 'js/loading.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sideknee_model_player1.js' %}"></script>
<script type="text/javascript">
    //  이미지ß
    //  얼굴
    let maskimg = new Image();
    maskimg.src = "{% static 'img/item/ironman_sm.png' %}"

    // 손
    let handimg = new Image();
    handimg.src = "../static/img/item/ironman_Hand.png"

    init();
</script>


<script>
    // 데미지 값
    let result_score = 0;
    let game_switch = 0; // 0 - 시작전 , 1 - 시작 , 2 - 종료
    let sign_switch = 2; // 0 - Stand(준비상태) , 1 - Left or Right, 2 - 포즈 실행전

    const bgm = new Audio();

    var audio_pose = new Audio('../static/sound/Kommy_BasicAttack_Hit.wav');
    var audio_set = new Audio('../static/sound/Kommy_BasicAttack.wav');

    let count = 1;
    let time = 300; // 기준 시간

    bgm.src = "/static/sound/inspiring-8-bit-563.mp3";
    bgm.volume = 0.5;
    window.onload = function() {
        bgm.play();
    }
    
</script>

<div class='screen'>
    <span class="msg-text"></span>
    <span class="score-text">0 점</span>
    <div id='timer'></div>
    <canvas id="canvas"></canvas>
    <img id="monster" src="{% static 'img/monster/monster-jelly_0.gif' %}">
    <canvas id="canvas_hp"></canvas>
    <div id="label-container" style='right: 0%; width: 29.5%;'></div>
</div>

<form name="score_form" method="post" action="/result/">
    {% csrf_token %}
    <input type="hidden" id="score" name="score">
    <input type="hidden" id="option" name="option" value="{{ player }}">
    <input type="hidden" id="fitness_name" name="fitness_name" value="{{ exercise_name }}">
    <input type="hidden" id="user_name" name="user_name" value="{{ request.session.name }}">
    <input type="hidden" id="fitness_index" name="fitness_index" value="{{ fitness_index }}">
    <input type="hidden" id="user_index" name="user_index" value="{{ request.session.user_index }}">
    <input type="hidden" id="stage" name="stage">
</form>

<script type="text/javascript" src="{% static 'js/health-bar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/monster.js' %}"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>

{% endblock %}

templates/fitness/play2p.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_SD.css' %}"/>
<script type="text/javascript" src="{% static 'js/loading.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sideknee_model_player2.js' %}"></script>
<script type="text/javascript">
    //  이미지
    //  얼굴
    let maskimg = new Image();
    maskimg.src = "../static/img/item/ironman_sm.png"

    var audio_pose = new Audio('../static/sound/Kommy_BasicAttack_Hit.wav');
    var audio_set = new Audio('../static/sound/Kommy_BasicAttack.wav');

    // 손
    let handimg = new Image();
    handimg.src = "../static/img/item/ironman_Hand.png"

    init();
</script>

<script>
    // Damage Values
    let result_score = 0;
    let game_switch = 0; // 0 - 시작전 , 1 - 시작 , 2 - 종료
    let sign_switch = 2; // 0 - Stand(준비상태) , 1 - Left or Right, 2 - 포즈 실행전

    const bgm = new Audio();

    let count = 1;
    let time = 50; // 기준 시간
    

    bgm.src = "/static/sound/inspiring-8-bit-563.mp3";
    bgm.volume = 0.5;
    window.onload = function() {
        bgm.play();
    }
</script>

<div class='screen'>
    <span class="msg-text"></span>
    <span class="score-text">0 점</span>
    <div id='timer'></div>
    <canvas id="canvas"></canvas>
    <img id="monster" scr="img/monster-jelly_0.gif">
    <canvas id="canvas_hp"></canvas>
    <div id="label-container"></div>
    <div id="label-container2"></div>
</div>

<form name="score_form" method="post" action="/result/">
    {% csrf_token %}
    <input type="hidden" id="score" name="score">
    <input type="hidden" id="option" name="option" value="{{ player }}">
    <input type="hidden" id="fitness_name" name="fitness_name" value="{{ exercise_name }}">
    <input type="hidden" id="user_name" name="user_name" value="{{ request.session.name }}">
    <input type="hidden" id="fitness_index" name="fitness_index" value="{{ fitness_index }}">
    <input type="hidden" id="user_index" name="user_index" value="{{ request.session.user_index }}">
    <input type="hidden" id="stage" name="stage">
</form>

<script type="text/javascript" src="{% static 'js/health-bar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/monster.js' %}"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/fitness/player.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style_g1.css' %}"/>

<script>
    let bgm = new Audio();
    bgm.src = "/static/upright-piano-arcade-instrumental-mix-1342.mp3";
    bgm.play();

    let count = 1;
</script>



<form method='POST' action="{% url 'fitness:play' %}">
    {% csrf_token %}
    <div class="screen">
        <div>
            <img id="back" src="/static/img/select-back.png" onclick="go_select()">
            <h3 id="ex_name" style="display:inline;"></h3>
            <img id="audiobtn" src="/static/img/sound-on.png" onclick="play_pause()">
        </div><br><br>
        <div id="left">
            <img id="ex_img" src="" width='200px' height='200px'>
        </div>
        <div id="right">
            <div id="explain"></div>
            <div class='radio'>
                <div>
                    <input type="radio" id="rad1" name="selected_p" value='1' required>
                    <label for="rad1"></label>
                    <p>1인</p>
                </div>
                <div>
                    <input type="radio" id="rad2" name="selected_p" value='2'>
                    <label for="rad2"></label>
                    <p>2인</p>
                </div>
            </div>
            <button type='submit' id="playbtn">PLAY</button>
        </div>
        <input type='hidden' id="exercise" name='exercise'>
    </div>
</form>
{% endblock %}

templates/fitness/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_Result.css' %}" />
<body>
    <div class='screen'>
        <p style='color:white; font-size: xx-large;'>결과 화면</p> <br>
        <table id='tb-result' class="table table-borderless">
            <thead style="color:white; font-size: x-large;">
                <tr>
                    <th>등수</th>
                    <th>이름</th>
                    <th>운동</th>
                    <th>스테이지</th>
                    <th>1인/2인</th>
                    <th>점수</th>
                </tr>
            </thead>
            <tbody style="color:white; font-size: large;">
                {% for i in '1234567' %}
                    {% if i != '4' %}
                    <tr>
                        <td class="row_num">{{ i }}</td>
                        <td class="rank_user_name"></td>
                        <td class="rank_fitness_name"></td>
                        <td class="stage"></td>
                        <td class="option"></td>
                        <td class="rank_score"></td>
                    </tr>
                    {% else %}
                    <tr style="color:red;">
                        <td class="row_num">{{ i }}</td>
                        <td class="rank_user_name"></td>
                        <td class="rank_fitness_name"></td>
                        <td class="stage"></td>
                        <td class="option"></td>
                        <td class="rank_score"></td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>

        </table>
        <br>
        <input type="button" value="CONTINUE" onclick="location.href = '../select'"></input>
        <input type="button" value="CLOSE" onclick="location.href = '../'"></input>
    </div>

</body>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    const get_result = () => {
        const result = axios({
            url: 'https://withfit.ml:8000/get_result/',
            method: 'get'
        });
        result.then((context) => {
            const data = context.data;
            // const user_index = "{{ user_index }}";
            // let my_pk = 9999;

            // for (let i = 0; i < data.result_data.length; i++) {
            //     if(data.result_data[i].pk == user_index){
            //         my_rank = i;
            //         break;
            //     }
            // }
            // console.log(my_pk);

            rank_user_name = document.getElementsByClassName('rank_user_name');
            rank_fitness_name = document.getElementsByClassName('rank_fitness_name');
            stage = document.getElementsByClassName('stage');
            option = document.getElementsByClassName('option');
            rank_score = document.getElementsByClassName('rank_score');

            for (let i = 0; i < 7; i++) {
                rank_user_name[i].innerHTML = data.result_data[i].rank_user_name;
                rank_fitness_name[i].innerHTML = data.result_data[i].rank_fitness_name;
                stage[i].innerHTML = data.result_data[i].stage;
                option[i].innerHTML = data.result_data[i].option + "인";
                rank_score[i].innerHTML = data.result_data[i].rank_score + "점";
            }
        });
    }
    get_result();
</script>

{% endblock %}

templates/fitness/select.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static '/css/style_g1.css' %}"/>
<script tpye="text/javascript"  src="{% static 'js/main.js' %}"></script>
<script>
    // main으로 이동
    function go_main() {
        history.back();
        return false;
    }

    // 운동 선택으로 이동
    function go_select() {
        fetch('/select/').then(function(response) {
            response.text().then(function(text) {
                document.querySelector('body').innerHTML = text;
            })
        })
    };

    // bgm play
    let bgm = new Audio();
    bgm.src = "/static/sound/upright-piano-arcade-instrumental-mix-1342.mp3";
    bgm.play();

    let count = 1;

    // bgm play, pause
    function play_pause() {
        console.log("play pause load")
        if (count == 0) {
            count = 1;
            bgm.play();
            document.getElementById('audiobtn').src = '/static/img/sound-on.png';
        }
        else {
            count = 0;
            bgm.pause();
            document.getElementById('audiobtn').src = '/static/img/sound-off.png';
        };
    };

    // withfit.html -> people.html
    function select_exercise(exercise) {
        const selected_exercise = exercise.value;
        let exercise_img;
        let guide;
        console.log(selected_exercise);

        if (selected_exercise == "푸시업") {
            exercise_img = "push_up";
            guide = "바닥에 엎드려서 양 손을 어깨너비로 벌리고 팔을 뻗고 시작합니다.<br>가슴이 바닥에 닿을 때까지 몸을 숙입니다.<br>잠깐 멈추었다가 다시 일어나는 것을 반복합니다.";
        } else if (selected_exercise == "사이드 런지") {
            exercise_img = "side_lunge";
            guide = "손을 모으고 어깨를 폅니다.<br>한 다리를 바깥으로 움직입니다.<br>반대쪽 다리를 곧게 펴고 살짝 앉은 후 제자리로 돌아갑니다.<br>반대쪽도 반복합니다.";
        } else if (selected_exercise == "스탠딩 니 업") {
            exercise_img = "standing_knee_up";
            guide = "발을 어깨너비로 하고 섭니다.<br>무릎을 최대한 높이 들어 올리기 위해 복근을 긴장시킵니다.<br>양 쪽 무릎을 번갈아가며 운동합니다.";
        } else {
            exercise_img = "step_forward_lunge";
            guide = "발을 엉덩이 너비로 벌리고 서서 한 쪽 다리를 크게 앞으로 움직입니다.<br>허벅지가 바닥과 평행하고 정강이와 수직이 될 때까지 앉습니다.<br>제자리로 돌아갑니다.";
        };
        console.log(exercise_img);
        
        fetch('/player/').then(function(response) {
            response.text().then(function(text) {
                document.querySelector('section').innerHTML = text;
                document.getElementById('ex_img').src = `/static/img/fitness/${exercise_img}.gif`;
                document.getElementById("explain").innerHTML = guide;
                document.getElementById('ex_name').innerHTML = selected_exercise;
                document.getElementById('exercise').value = selected_exercise;
            })
        })
    };
</script>

<section id="select">
    <div class="screen">
        <div>
            <img id="back" src="/static/img/select-back.png" onclick="go_main()">
            <h3 style="display:inline;">운동 선택</h3>
            <img id="audiobtn" src="/static/img/sound-on.png" onclick="play_pause()">
        </div><br><br>
        <form method='POST'>
            {% csrf_token %}
            <div class="select_exercise">
                <div class="exercise">
                    <img src="/static/img/fitness/push_up.gif">
                    <input type="button" value="푸시업" onclick="select_exercise(this)">
                </div>
                <div class="exercise">
                    <img src="/static/img/fitness/side_lunge.gif">
                    <input type="button" value="사이드 런지" onclick="select_exercise(this)">
                </div>
                <div class="exercise">
                    <img src="/static/img/fitness/standing_knee_up.gif">
                    <input type="button" value="스탠딩 니 업" onclick="select_exercise(this)">
                </div>
                <div class="exercise">
                    <img src="/static/img/fitness/step_forward_lunge.gif">
                    <input type="button" value="포워드 런지" onclick="select_exercise(this)">
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}